# Generated by Django 5.1.7 on 2025-04-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bladna', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='parent_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
