# Generated by Django 5.1.7 on 2025-04-26 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bladna', '0003_alter_user_parent_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, choices=[('South', 'south'), ('East', 'east'), ('Center', 'center'), ('Ouest', 'ouest')], default='south', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('South', 'south'), ('East', 'east'), ('Center', 'center'), ('Ouest', 'ouest')], max_length=10)),
                ('score', models.PositiveIntegerField()),
                ('play_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
